name: Test commit

on: push

jobs:
  test-ubuntu:
    name: pytest (Ubuntu)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.7
          - 3.8-dev
    steps:
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install sqlalchemy requests colorama beautifulsoup4
         pip install pytest
     - name: Do pytest
       env:
         librus_email: ${{ secrets.librus_email }}
         librus_passwrod: ${{ secrets.librus_password }}
       run: |
         pytest
  test-win:
    name: pytest (Windows)
    runs-on: windows-latest
    strategy:
      matrix:
        python-version:
          - 3.7
          - 3.8-dev
      steps:
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install sqlalchemy requests colorama beautifulsoup4
            pip install pytest
        - name: Do pytest
          env:
            librus_email: ${{ secrets.librus_email }}
            librus_passwrod: ${{ secrets.librus_password }}
          run: |
            pytest
