name: Test commit

on: push

jobs:
  test:
    name: pytest
    runs-on:
      - ubuntu-latest
      - windows-latest
      - macOS-latest
    strategy:
      matrix:
        - 3.7
        - 3.8-dev
    steps:
     - name: Install deps
       run: |
         pip install sqlalchemy requests colorama beautifulsoup4
     - name: Do pytest
       env:
         librus_email: ${{ secrets.librus_email }}
         librus_passwrod: ${{ secrets.librus_password }}
       run: |
         pip install pytest
         pytest
