name: Do tests

on: push

jobs:
  pytest-job:
    name: Pytest
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        python:
          - 3.7
          - 3.8-dev
    steps:
      - name: Install test requirements
        run: pip3 install setuptools
      - name: Install librus-tricks requirements
        run: pip3 install requests beautifulsoup4 SQLAlchemy
      - name: Test librus-tricks
        env:
          librus_email: ${{ secrets.librus_email }}
          librus_password: ${{ secrets.librus_password }}
        run: |
          pip3 install pytest
          pytest
